### ISSUE TITLE
Measure Criticality

### ISSUE THREAD

**Issue by thiagolims** [iocenter/FieldOpt-Research#12]
Implement method measureCriticality() in the TrustRegionModel class

**Comment by Bellout** [comment]
CriticalityMeasure is currently embedded in criticalityStep(), no need at this point for a separate function. Issue can be closed.

**Comment by thiagolims** [comment]
After manual testing, it seems to be working (code from @Bellout  =)). I'll test it later on in the main iteration of the TR algorithm.
