### ISSUE TITLE
Handle function evaluations within ensureImprovement() in iterate()

### ISSUE THREAD

**Issue by thiagolims** [iocenter/FieldOpt-Research#28]

**Comment by thiagolims** [comment]
@Bellout: we are getting a warning when solve the trust region problem:

┃ WARNING  ┃ Module: minimizeTr   ┃ Class: TrustRegionModel          ┃
┣━━━━━━━━━━━┻━━━━━━━━━━━━━━━━━━━━━━┻━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫
┃ X > 1 in EPS(X).  

Can you please double-check this part of the function ?

**Comment by Bellout** [comment]
Yes, I've seen it. Will give it a check. Don't think it is critical at this point, but needs to be resolved. Stuck on a bug for the meantime...
