### ISSUE TITLE
[Test] Test of initial (pivot and modeling) polynomial against CG-Matlab problem set

### ISSUE THREAD

**Issue by Bellout** [iocenter/FieldOpt-Research#6]
Make test that compares coefficients of initial polynomial models for all cg-test-problems against those computed using matlab code.

**Comment by thiagolims** [comment]
Adding model data for tests: see 2a4f6955d0af33814836d3c678f559613414f7ec  (Bellout)

**Comment by thiagolims** [comment]
@Bellout Isn't this already implemented in the tests ? Should we test the initial polynomials of all problems in CG-Matlab prob set ?

**Comment by Bellout** [comment]
The polynomial CG data is stored in dc_5test_tr-model-data.hpp. Polynomial testing is also implemented and can be turned on for the CG problems.
